# Generated by Django 4.2 on 2025-04-29 20:18

from django.db import migrations


def create_periodic_tasks(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # 1) every day at midnight → mark overdue
    midnight, _ = CrontabSchedule.objects.get_or_create(
        minute="0", hour="0", day_of_week="*", day_of_month="*", month_of_year="*"
    )
    PeriodicTask.objects.get_or_create(
        name="Mark Overdue Installments",
        task="bnpl.tasks.mark_overdue_installments",
        crontab=midnight,
        defaults={"enabled": True},
    )

    # 2) every day at 08:00 → send reminders
    morning, _ = CrontabSchedule.objects.get_or_create(
        minute="0", hour="8", day_of_week="*", day_of_month="*", month_of_year="*"
    )
    PeriodicTask.objects.get_or_create(
        name="Send Due Reminders",
        task="bnpl.tasks.send_due_reminders",
        crontab=morning,
        defaults={"enabled": True},
    )


def delete_periodic_tasks(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(
        name__in=["Mark Overdue Installments", "Send Due Reminders"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("bnpl", "0001_initial"),
    ]

    operations = []
